server:

  port: 8081
  servlet:
    context-path: /api



spring:
  ai:
    openai:
      api-key: "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"
    chat:
      client:
        enabled: true
      model: gpt-4
    vectorstore:
       elasticsearch:
        index-name: document-total-11-01-03
        initialize-schema: true
  datasource:
    url: "jdbc:mysql://localhost:3306/chatbotdb"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds





